# Generated by Django 5.2.1 on 2025-05-14 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(unique=True, verbose_name=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Iltimos, telefon raqamini +998901234567 formatida kiriting.', regex='^\\+?998\\d{9}$')]))),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
