# Generated by Django 5.2.1 on 2025-05-14 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Iltimos, telefon raqamini +998901234567 formatida kiriting.', regex='^\\+?998\\d{9}$')]),
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.user')),
            ],
        ),
    ]
